version: '3.5'

services:
  zeit:
    image: zeit
    container_name: zeit
    environment:
      ZEIT_TOKEN: "$ZEIT_TOKEN"
      NOW_ORG_ID: "$NOW_ORG_ID"
      NOW_PROJECT_ID: "$NOW_PROJECT_ID"
    ports:
        - 3000:3000
    restart: always
    volumes:
      - .:/root/project